---
## add stack

- name: add stack
  uri:
    url: http://che-{{ project_name }}.{{ route_suffix }}/api/stack
    method: POST
    body: "{{ stack_json }}"
    body_format: json
    status_code: 200,201