---
## Eclipse Che Web IDE Install

- name: check if eclipse che project {{ project_name }} exists
  shell: "{{ openshift_cli }} get project {{ project_name }}"
  register: project_result
  ignore_errors: true
  changed_when: false

- name: create eclipse che project {{ project_name }}
  shell: "{{ openshift_cli }} new-project {{ project_name }} --display-name='{{ project_display_name }}' --description='{{ project_desc }}'"
  when: project_result|failed

- name: assign user as project admin
  shell: "{{ openshift_cli }} adm policy add-role-to-user admin {{ project_admin }} -n {{ project_name }}"
  ignore_errors: true
  when: 
    - project_result|failed
    - project_admin is defined
    - project_admin is not none
    - project_admin|trim() != ""

- name: annotate eclipse che project {{ project_name }}
  shell: "{{ openshift_cli }} annotate --overwrite namespace {{ project_name }} {{ project_annotations }}"
  ignore_errors: true
  when:
    - project_result|failed
    - project_annotations is defined
    - project_annotations is not none
    - project_annotations|trim() != ""    

- include_tasks: single_user.yml
  when: not multi_user|bool

- include_tasks: multi_user.yml
  when: multi_user|bool
