---
## Eclipse Che Web IDE Install - Single User

# import eclispe che template
- name: import eclipse che template
  shell: "{{ openshift_cli }} apply -f https://raw.githubusercontent.com/minishift/minishift/master/addons/che/templates/che-single-user.yml -n {{ project_name }}"

# install eclipse che
- name: deploy eclipse che template
  shell: "{{ openshift_cli }} new-app che-single-user -n {{ project_name }} -p IMAGE_CHE_SERVER=eclipse/che-server:{{ che_version }} -p PROJECT_NAME={{ project_name }} -p DOMAIN_NAME={{ route_suffix }}"
  ignore_errors: true

- name: adjust eclipse che resources
  shell: |
    {{ openshift_cli }} set probe dc/che --readiness --initial-delay-seconds=60 --failure-threshold=10 --period-seconds=30 -n {{ project_name }}
    {{ openshift_cli }} set probe dc/che --liveness --initial-delay-seconds=180 --failure-threshold=10 --period-seconds=30 -n {{ project_name }}
    {{ openshift_cli }} set resources dc/che --requests=cpu=200m,memory=512Mi --limits=cpu=2,memory=2Gi -n {{ project_name }}
  ignore_errors: true

- include_tasks: add_stack_single.yml
  vars:
    stack_json: "{{ lookup('file','files/default-java-stack.json') }}"
  when: install_java_oc_stack|bool

- include_tasks: add_stack_single.yml
  vars:
    stack_json: "{{ item }}"
  loop: "{{ install_custom_stacks_json }}"
  when:
    - install_custom_stacks_json is defined
    - install_custom_stacks_json is not none
    - install_custom_stacks_json|trim() != ""
